config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    member do
      get :bookmark
    end
  end

  devise_for :users do
    resources :profiles
  end

  resources :profiles do
    resources :favorites
    resources :follows
  end

  resources :brands do
    resources :products
  end
  resources :products

  # resources :components
  # resources :active_effects
  resources :comments
  get '/catalog', to: 'products#index', as: :catalogs
  get 'catalog/:id', to: 'products#catalog', as: :catalog
  # resources :products do
  # end

  # root"detach#landing"
  # get 'detach/landing'
  root"detach#index"
  get 'detach/index'

  get 'detach/landing'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
      can :read, Detach
      can :read, Article
      can :read, Brand
      can :read, Favorite
      can :read, Product
    elsif user.persisted?
      can :manage, Profile, id: user.profile.id
      can :read, Detach
      can :read, Article
      can :read, Brand
      can :manage, Favorite
      can :read, Product
    else
      can :read, Detach
      can :read, Article
      can :read, Brand
      can :manage, Favorite
      can :read, Product
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/active_effect.rb
class ActiveEffect < ApplicationRecord
  has_many :property
  has_many :components, through: :property

  has_many :product_promise
  has_many :products, through: :product_promise

  has_many :skin_type_factors
  has_many :skin_types, through: :skin_type_factor

  validates :name, uniqueness: true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :bookmarks
  has_many :profiles, through: :bookmarks

  mount_uploader :cover, CoverUploader
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :profile
  belongs_to :article
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products

  mount_uploader :logo, BrandsLogoUploader

  validates :name, uniqueness: true

  has_many :follows
  has_many :profiles, through: :following

end

app/models/comment.rb
class Comment < ApplicationRecord
  # belongs_to :products
  # belongs_to :profiles
end

app/models/component.rb
class Component < ApplicationRecord
  has_many :property
  has_many :products, through: :structure
  has_many :active_effects, through: :property

  validates :name, uniqueness: true

end

app/models/detach.rb
class Detach
end

app/models/diet.rb
class Diet < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :profile
  belongs_to :product
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :profile
  belongs_to :brand
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand

  has_many :comments
  # has_many :profiles, through: :comments

  has_many :structure
  has_many :components, through: :structure

  has_many :product_promise
  has_many :active_effects, through: :product_promise

  has_many :favorites
  # has_many :users, through: :favorites

  has_many :product_types
  has_many :products_groups, through: :product_types

  mount_uploader :image, ProductImagesUploader

  validates :name, uniqueness: true

end

app/models/product_group.rb
class ProductGroup < ApplicationRecord
  has_many :product_types
  has_many :products, through: :product_types
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  belongs_to :product
  belongs_to :product_group
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_many :comments
  # has_many :products, through: :comments

  has_many :favorites
  has_many :products, through: :favorites

  has_many :follows
  has_many :brands, through: :following

  has_many :bookmarks
  has_many :articles, through: :bookmarks

  belongs_to :skin_type, optional: true

  mount_uploader :avatar, AvatarUploader
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :component
  belongs_to :active_effect
end

app/models/skin_factor.rb
class SkinFactor < ApplicationRecord

end

app/models/skin_type.rb
class SkinType < ApplicationRecord
  has_one :profile

  has_many :skin_type_factors
  has_many :active_effects, through: :skin_type_factor
end

app/models/structure.rb
class Structure < ApplicationRecord
  belongs_to :product
  belongs_to :component
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile

  has_many :favorites
  has_many :products, through: :favorites

  after_create :create_profile

  def create_profile
    Profile.create!(user_id: self.id, name: 'Введите имя пользователя')
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  load_and_authorize_resource
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:name, :user_id)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="point">
    <%= form.text_field :name %>
  </div>
  <div class="point">
    <%= form.text_field :name %>
  </div>
  <div class="point">
    <%= form.number_field :age %>
  </div>
  <div class="but">
    <%= form.file_field :avatar %>
  </div>

  <div class="point">
    <%= form.select( :skin_type_id, SkinType.all.collect{ |skin| [skin.name, skin.id]}) %>
  </div>

  <h3>Дополнительная информация</h3>

  <div class="but">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Личная информация</h1>
<div class="profile">
    <div class="cover">
      <div class="image">
        <% if @profile.avatar.url %>
          <%= image_tag @profile.avatar.url %>
        <% else %>
          <%= image_tag asset_path("apsent.jpg") %>
        <% end %>
        <div class="strouke"></div>
      </div>
      <div class="nav">
        <ul>
          <li>
            <%= link_to "Избранное", profile_favorites_path(@profile) %>
          </li>
          <li>
            <%= link_to "Редактировать", edit_profile_path(@profile)%>
          </li>
          <li>
            <%= link_to "Изменить пароль", edit_profile_path %>
          </li>
          <li>
            <%= link_to('Выйти', destroy_user_session_path, method: :delete) %>
          </li>
        </ul>
      </div>
    </div>
    <div class="info">
      <%= render 'form', profile: @profile %>
      <%= link_to 'Отмена', profile_path(@profile) %>

    </div>
</div>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.user_id %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<h1>Личная информация</h1>
<div class="profile">
    <div class="cover">
      <div class="image">
        <% if @profile.avatar.url %>
          <%= image_tag @profile.avatar.url %>
        <% else %>
          <%= image_tag asset_path("apsent.jpg") %>
        <% end %>
        <div class="strouke"></div>
      </div>
      <div class="nav">
        <ul>
          <li>
            <h4><%= link_to "Избранное", profile_favorites_path(@profile) %></h4>
          </li>
          <li>
            <h4><%= link_to "Редактировать", edit_profile_path(@profile)%></h4>
          </li>
          <li>
            <h4><%= link_to "Изменить пароль", edit_profile_path %></h4>
          </li>
          <li>
            <h4><%= link_to('Выйти', destroy_user_session_path, method: :delete) %></h4>
          </li>
        </ul>
      </div>
    </div>
    <div class="info">
      <div class="point">
        <p><%= @profile.name %></p>
      </div>
      <div class="point">
        <p><%= @profile.user.email %></p>
      </div>
      <div class="point">
        <p><%= @profile.age %></p>
      </div>
      <div class="point">
        <p><%= @profile.skin_type.name unless @profile.skin_type == nil %></p>
      </div>

      <h3>Дополнительная информация</h3>

    </div>
</div>