config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    member do
      get :bookmark
    end
  end

  devise_for :users do
    resources :profiles
  end

  resources :profiles do
    resources :favorites
    resources :follows
  end

  resources :brands do
    resources :products
  end
  resources :products

  # resources :components
  # resources :active_effects
  resources :comments
  get '/catalog', to: 'products#index', as: :catalogs
  get 'catalog/:id', to: 'products#catalog', as: :catalog
  # resources :products do
  # end

  # root"detach#landing"
  # get 'detach/landing'
  root"detach#index"
  get 'detach/index'

  get 'detach/landing'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
      can :read, Detach
      can :read, Article
      can :read, Brand
      can :read, Favorite
      can :read, Product
    elsif user.persisted?
      can :manage, Profile, id: user.profile.id
      can :read, Detach
      can :read, Article
      can :read, Brand
      can :manage, Favorite
      can :read, Product
    else
      can :read, Detach
      can :read, Article
      can :read, Brand
      can :manage, Favorite
      can :read, Product
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/active_effect.rb
class ActiveEffect < ApplicationRecord
  has_many :property
  has_many :components, through: :property

  has_many :product_promise
  has_many :products, through: :product_promise

  has_many :skin_type_factors
  has_many :skin_types, through: :skin_type_factor

  validates :name, uniqueness: true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :bookmarks
  has_many :profiles, through: :bookmarks

  mount_uploader :cover, CoverUploader
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :profile
  belongs_to :article
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products

  mount_uploader :logo, BrandsLogoUploader

  validates :name, uniqueness: true

  has_many :follows
  has_many :profiles, through: :following

end

app/models/comment.rb
class Comment < ApplicationRecord
  # belongs_to :products
  # belongs_to :profiles
end

app/models/component.rb
class Component < ApplicationRecord
  has_many :property
  has_many :products, through: :structure
  has_many :active_effects, through: :property

  validates :name, uniqueness: true

end

app/models/detach.rb
class Detach
end

app/models/diet.rb
class Diet < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :profile
  belongs_to :product
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :profile
  belongs_to :brand
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand

  has_many :comments
  # has_many :profiles, through: :comments

  has_many :structure
  has_many :components, through: :structure

  has_many :product_promise
  has_many :active_effects, through: :product_promise

  has_many :favorites
  # has_many :users, through: :favorites

  has_many :product_types
  has_many :products_groups, through: :product_types

  mount_uploader :image, ProductImagesUploader

  validates :name, uniqueness: true

end

app/models/product_group.rb
class ProductGroup < ApplicationRecord
  has_many :product_types
  has_many :products, through: :product_types
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  belongs_to :product
  belongs_to :product_group
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_many :comments
  # has_many :products, through: :comments

  has_many :favorites
  has_many :products, through: :favorites

  has_many :follows
  has_many :brands, through: :following

  has_many :bookmarks
  has_many :articles, through: :bookmarks

  belongs_to :skin_type, optional: true

  mount_uploader :avatar, AvatarUploader
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :component
  belongs_to :active_effect
end

app/models/skin_factor.rb
class SkinFactor < ApplicationRecord

end

app/models/skin_type.rb
class SkinType < ApplicationRecord
  has_one :profile

  has_many :skin_type_factors
  has_many :active_effects, through: :skin_type_factor
end

app/models/structure.rb
class Structure < ApplicationRecord
  belongs_to :product
  belongs_to :component
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile

  has_many :favorites
  has_many :products, through: :favorites

  after_create :create_profile

  def create_profile
    Profile.create!(user_id: self.id, name: 'Введите имя пользователя')
  end
end

app/controllers/detach_controller.rb
class DetachController < ApplicationController
  def index
  end

end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/detach/index.html.erb
<div class="mainCover">
  <% Article.find() do |art| %>
    <div class="info">
      <h1><%= art.header %></h1>
      <p><%= art.description %></p>
      <%= render "but", mes: "Читать статью", rout: article_path(art.id), method: :get %>
    </div>
    <div class="">
      <%= image_tag(asset_path("cover.jpg")) %>

    </div>
  <% end %>
</div>


<% mes = 'Показать все' %>

<%= render "products/productBlock", h2: "Новинки", cla: Product, cardType: "products/productCard", mes: mes, rout: catalogs_path, method: :get %>

<%= render "products/productBlock", h2: "Бренды", cla: Brand, cardType: "brands/brandCard", mes: mes, rout: brands_path, method: :get %>

<%= render "articles/articleBlock", h2: "Статьи", cla: Article, cardType: "articles/articleCard", mes: mes, rout: articles_path, method: :get %>

app/views/detach/landing.html.erb
<div class="landing">
  <div class="info">
    <%= image_tag(asset_path("forLanding/header.png"), :class => "first") %>
    <div class="skreen">
      <div class="content">
        <h1>Истинная красота начинается со здоровья</h1>
        <p>Глаза – зеркало души, а кожа – зеркало здоровья. Сервис Detach, основываясь на советах профессионалов бьюти-индустрии, поможет грамотно ухаживать за кожей. </p>
        <%= render 'but', mes: 'Подобрать продукт', rout: catalogs_path, method: :get %>
      </div>
    </div>
    <div class="skreen">
      <div class="content">
        <h1>Каждая деталь имеет значение</h1>
        <p>Каждый человек уникален, поэтому при выборе косметических продуктов важно уделить внимание особенностям кожи. Расскажите о себе в профиле или пройдите тест для определения типа кожи, чтобы подобрать подходящую продукцию. </p>
        <%= render 'but', mes: 'Узнать тип кожи', rout: detach_index_path, method: :get %>
      </div>

      <%= image_tag(asset_path("forLanding/mobile.png")) %>
    </div>
    <div class="skreen">
      <div class="column">
        <div class="img">
          <%= image_tag(asset_path("forLanding/symb1.png")) %>
        </div>
        <h3>Совершайте покупки с выгодой</h3>
        <p>Не отказывайте себе в покупке любимых косметических средств. Приобретайте выгодно, сравнивая цены в интернет-магазинах через наш сервис.</p>
      </div>
      <div class="column">
        <div class="img">
          <%= image_tag(asset_path("forLanding/symb2.png")) %>
        </div>
        <h3>Узнавайте больше нового о мире бьюти</h3>
        <p>В статьях собрана информация, которая поможет разобраться в тонкостях производства косметической продукции.</p>
      </div>
      <div class="column">
        <div class="img">
          <%= image_tag(asset_path("forLanding/symb3.png")) %>
        </div>
        <h3>Ваш выбор всегда верный</h3>
        <p>Проверьте эффективность и состав продукта и будьте уверены в выборе косметического средства.</p>
      </div>
    </div>
    <div class="skreen">
      <div class="content">
        <h1>Природная красота – ключ к гармонии</h1>
        <p>Проверьте продукцию и упаковку на этичность и позаботьтесь о природе вместе с нашим сервисом.</p>
        <%= render 'but', mes: 'Проверить продукт', rout: catalogs_path, method: :get %>
      </div>
      <%= image_tag(asset_path("forLanding/table.png")) %>
    </div>
    <div class="skreen">
      <div class="content">
        <h1>Уверенность – это верность себе</h1>
        <p>Уверенность – неотъемлемый этап на пути любви к себе. Ознакомьтесь с информацией о составе понравившегося продукта и забудьте о сомнениях, связанных с эффективностью товара.</p>
        <%= render 'but', mes: 'Пройти тест', rout: detach_index_path, method: :get %>
      </div>
      <div class="image">
        <%= image_tag(asset_path("forLanding/table2.png")) %>
      </div>
    </div>
    <div class="skreen">
      <div class="content">
        <h1>Совершенство – это не мастерство, а отношение</h1>
        <p>Detach сотрудничает с экспертами бьюти-индустрии, которые уделяют внимание каждой детали, чтобы подобрать продукт под ваши особенности. Пройдите тест на определение типа кожи от нашего эксперта.</p>
        <%= render 'but', mes: 'Пройти тест', rout: detach_index_path, method: :get %>
      </div>
      <div class="image">
        <%= image_tag(asset_path("forLanding/ann.png")) %>
        <span></span>
      </div>
    </div>
  </div>
  <div class="fot">
    <%= image_tag(asset_path("forLanding/footer.png")) %>
    <div class="content">
      <h1>Забота о себе и своем здоровье еще проще с нашим приложением</h1>
      <%= image_tag(asset_path("forLanding/app.png")) %>
    </div>
  </div>
</div>