config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    member do
      get :bookmark
    end
  end

  devise_for :users do
    resources :profiles
  end

  resources :profiles do
    resources :favorites
    resources :follows
  end

  resources :brands do
    resources :products
  end
  resources :products

  # resources :components
  # resources :active_effects
  resources :comments
  get '/catalog', to: 'products#index', as: :catalogs
  get 'catalog/:id', to: 'products#catalog', as: :catalog
  # resources :products do
  # end

  # root"detach#landing"
  # get 'detach/landing'
  root"detach#index"
  get 'detach/index'

  get 'detach/landing'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
      can :read, Detach
      can :read, Article
      can :read, Brand
      can :read, Favorite
      can :read, Product
    elsif user.persisted?
      can :manage, Profile, id: user.profile.id
      can :read, Detach
      can :read, Article
      can :read, Brand
      can :manage, Favorite
      can :read, Product
    else
      can :read, Detach
      can :read, Article
      can :read, Brand
      can :manage, Favorite
      can :read, Product
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/active_effect.rb
class ActiveEffect < ApplicationRecord
  has_many :property
  has_many :components, through: :property

  has_many :product_promise
  has_many :products, through: :product_promise

  has_many :skin_type_factors
  has_many :skin_types, through: :skin_type_factor

  validates :name, uniqueness: true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :bookmarks
  has_many :profiles, through: :bookmarks

  mount_uploader :cover, CoverUploader
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :profile
  belongs_to :article
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products

  mount_uploader :logo, BrandsLogoUploader

  validates :name, uniqueness: true

  has_many :follows
  has_many :profiles, through: :following

end

app/models/comment.rb
class Comment < ApplicationRecord
  # belongs_to :products
  # belongs_to :profiles
end

app/models/component.rb
class Component < ApplicationRecord
  has_many :property
  has_many :products, through: :structure
  has_many :active_effects, through: :property

  validates :name, uniqueness: true

end

app/models/detach.rb
class Detach
end

app/models/diet.rb
class Diet < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :profile
  belongs_to :product
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :profile
  belongs_to :brand
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand

  has_many :comments
  # has_many :profiles, through: :comments

  has_many :structure
  has_many :components, through: :structure

  has_many :product_promise
  has_many :active_effects, through: :product_promise

  has_many :favorites
  # has_many :users, through: :favorites

  has_many :product_types
  has_many :products_groups, through: :product_types

  mount_uploader :image, ProductImagesUploader

  validates :name, uniqueness: true

end

app/models/product_group.rb
class ProductGroup < ApplicationRecord
  has_many :product_types
  has_many :products, through: :product_types
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  belongs_to :product
  belongs_to :product_group
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_many :comments
  # has_many :products, through: :comments

  has_many :favorites
  has_many :products, through: :favorites

  has_many :follows
  has_many :brands, through: :following

  has_many :bookmarks
  has_many :articles, through: :bookmarks

  belongs_to :skin_type, optional: true

  mount_uploader :avatar, AvatarUploader
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :component
  belongs_to :active_effect
end

app/models/skin_factor.rb
class SkinFactor < ApplicationRecord

end

app/models/skin_type.rb
class SkinType < ApplicationRecord
  has_one :profile

  has_many :skin_type_factors
  has_many :active_effects, through: :skin_type_factor
end

app/models/structure.rb
class Structure < ApplicationRecord
  belongs_to :product
  belongs_to :component
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile

  has_many :favorites
  has_many :products, through: :favorites

  after_create :create_profile

  def create_profile
    Profile.create!(user_id: self.id, name: 'Введите имя пользователя')
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  load_and_authorize_resource
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def brand_params
      params.require(:brand).permit(:name, :description, :site, :logo)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/brands/_brandCard.html.erb
<%= link_to(brand_path(mod.id)) do %>
  <div class="brandCard">
    <%= image_tag mod.logo.url unless mod.logo.url == nil %>
    <h3><%= mod.name %></h3>
  </div>
<% end %>

app/views/brands/_form.html.erb
<%= form_with(model: brand, local: true) do |form| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
        <% brand.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :site %>
    <%= form.text_field :site %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<div class="brands">
  <div class="brands_fav">
    <h1>Бренды</h1>

    <% if current_user %>
      <% if Profile.find(current_user.id).follows.count > 0 %>
      <% Profile.find(current_user.id).follows.all.each do |follow| %>
      <% brand = Brand.find(follow.brand_id) %>
      <div class="brand">
        <%= link_to brand do%>
        <p><%= brand.name %></p>
        <% end %>
        <%= link_to profile_follows_path(profile_id: current_user.profile.id, brand_id: brand.id), method: :post  do%>
        <%= image_tag asset_path("icons/follow/inactiveDarc.png") %>
        <% end %>
      </div>
      <% end %>
      <% else %>
      <p>Добавьте любимый бренд в избранное чтобы следить за его новинками</p>
      <% end %>
    <% else %>
      <p>Добавьте любимый бренд в избранное чтобы следить за его новинками</p>
    <% end %>



  </div>

  <div class="brands_list">
    <% brands = Array.new %>
    <% @brands.all.each do |brand| %>
      <% brands.push(brand.name) %>
    <% end %>
    <% brands = brands.sort %>
    <% a = brands[0][0] %>
    <h1><%= a %></h1>
    <div class="brands_grup">
    <% brands.each do |brand_name| %>
      <% if brand_name[0] == a %>
        <div class="brand">
          <% brand = Brand.find_by name: brand_name %>
          <% if current_user %>
            <%= link_to profile_follows_path(profile_id: current_user.profile.id, brand_id: brand.id), method: :post do %>
              <%= image_tag asset_path("icons/follow/inactiveDarc.png") %>
            <% end %>
          <% else %>
            <%= link_to new_user_session_path do%>
              <%= image_tag asset_path("icons/follow/inactiveDarc.png") %>
            <% end %>
          <% end %>
          <%= link_to brand do%>
            <p><%= brand.name %></p>
          <% end %>
        </div>
      <% else %>
    </div>
    <% a = brand_name[0] %>
    <h1><%= a %></h1>
    <div class="brands_grup">
          <div class="brand">
            <% brand = Brand.find_by name: brand_name %>
            <% if current_user %>
              <%= link_to profile_follows_path(profile_id: current_user.profile.id, brand_id: brand.id), method: :post  do%>
                <%= image_tag asset_path("icons/follow/inactiveDarc.png") %>
              <% end %>
            <% else %>
              <%= link_to new_user_session_path do%>
                <%= image_tag asset_path("icons/follow/inactiveDarc.png") %>
              <% end %>
            <% end %>
            <%= link_to brand do%>
              <p><%= brand.name %></p>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
    </div>
  </div>





<br>
<% if can? :edit, @post %>
  <%= render "but", mes: "Новый бренд", rout: new_brand_path, method: :get%>
<% end %>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<div class="brandPage">

  <div class="cover">
    <div class="image">
      <%= image_tag @brand.logo.url unless @brand.logo.url == nil %>
    </div>
    <div class="info">
      <h1><%= @brand.name %></h1>
      <h3>Описание бренда</h3>
      <p><%= @brand.description %></p>
      <div class="but">
        <% if current_user %>
          <%= render "but", mes: "Подписаться", rout: profile_follows_path(profile_id: current_user.profile.id, brand_id: @brand.id), method: :post %>
        <% else %>
          <%= render "but", mes: "Подписаться", rout: new_user_session_path, method: :get  %>
        <% end %>
        <% if can? :edit, @post %>
          <%= render "but", mes: "Редактировать", rout: edit_brand_path, method: :get %>
        <% end %>
      </div>

    </div>
  </div>
  <div class="but">
    <% if current_user %>
      <%= render "but", mes: "Подписаться", rout:  profile_follows_path(profile_id: current_user.profile.id, brand_id: @brand.id), method: :post %>
    <% else %>
      <%= render "but", mes: "Подписаться", rout: new_user_session_path, method: :get %>
    <% end %>

    <% if can? :edit, @post %>
      <%= render "but", mes: "Редактировать", rout: edit_brand_path, method: :get %>
    <% end %>
  </div>

  <!-- <p><%#= @brand.site %></p> -->

  <h2>Продукты</h2>


  <div class="cardsCollection">
    <% @brand.products.each do |product|%>
      <%= render "products/productCard", mod: product %>
    <% end %>
  </div>
  <br>
  <%= render "but", mes: "Новый продукт", rout: new_brand_product_path(@brand), method: :get %>
</div>