config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    member do
      get :bookmark
    end
  end

  devise_for :users do
    resources :profiles
  end

  resources :profiles do
    resources :favorites
    resources :follows
  end

  resources :brands do
    resources :products
  end
  resources :products

  # resources :components
  # resources :active_effects
  resources :comments
  get '/catalog', to: 'products#index', as: :catalogs
  get 'catalog/:id', to: 'products#catalog', as: :catalog
  # resources :products do
  # end

  # root"detach#landing"
  # get 'detach/landing'
  root"detach#index"
  get 'detach/index'

  get 'detach/landing'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
      can :read, Detach
      can :read, Article
      can :read, Brand
      can :read, Favorite
      can :read, Product
    elsif user.persisted?
      can :manage, Profile, id: user.profile.id
      can :read, Detach
      can :read, Article
      can :read, Brand
      can :manage, Favorite
      can :read, Product
    else
      can :read, Detach
      can :read, Article
      can :read, Brand
      can :manage, Favorite
      can :read, Product
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/active_effect.rb
class ActiveEffect < ApplicationRecord
  has_many :property
  has_many :components, through: :property

  has_many :product_promise
  has_many :products, through: :product_promise

  has_many :skin_type_factors
  has_many :skin_types, through: :skin_type_factor

  validates :name, uniqueness: true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :bookmarks
  has_many :profiles, through: :bookmarks

  mount_uploader :cover, CoverUploader
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :profile
  belongs_to :article
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products

  mount_uploader :logo, BrandsLogoUploader

  validates :name, uniqueness: true

  has_many :follows
  has_many :profiles, through: :following

end

app/models/comment.rb
class Comment < ApplicationRecord
  # belongs_to :products
  # belongs_to :profiles
end

app/models/component.rb
class Component < ApplicationRecord
  has_many :property
  has_many :products, through: :structure
  has_many :active_effects, through: :property

  validates :name, uniqueness: true

end

app/models/detach.rb
class Detach
end

app/models/diet.rb
class Diet < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :profile
  belongs_to :product
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :profile
  belongs_to :brand
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand

  has_many :comments
  # has_many :profiles, through: :comments

  has_many :structure
  has_many :components, through: :structure

  has_many :product_promise
  has_many :active_effects, through: :product_promise

  has_many :favorites
  # has_many :users, through: :favorites

  has_many :product_types
  has_many :products_groups, through: :product_types

  mount_uploader :image, ProductImagesUploader

  validates :name, uniqueness: true

end

app/models/product_group.rb
class ProductGroup < ApplicationRecord
  has_many :product_types
  has_many :products, through: :product_types
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  belongs_to :product
  belongs_to :product_group
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_many :comments
  # has_many :products, through: :comments

  has_many :favorites
  has_many :products, through: :favorites

  has_many :follows
  has_many :brands, through: :following

  has_many :bookmarks
  has_many :articles, through: :bookmarks

  belongs_to :skin_type, optional: true

  mount_uploader :avatar, AvatarUploader
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :component
  belongs_to :active_effect
end

app/models/skin_factor.rb
class SkinFactor < ApplicationRecord

end

app/models/skin_type.rb
class SkinType < ApplicationRecord
  has_one :profile

  has_many :skin_type_factors
  has_many :active_effects, through: :skin_type_factor
end

app/models/structure.rb
class Structure < ApplicationRecord
  belongs_to :product
  belongs_to :component
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile

  has_many :favorites
  has_many :products, through: :favorites

  after_create :create_profile

  def create_profile
    Profile.create!(user_id: self.id, name: 'Введите имя пользователя')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_articleBlock.html.erb
<div class="block articles">
  <div class="pattern">
    <%#= image_tag(asset_path(@imagePath)) %>
  </div>
  <div class="content">
    <h2><%= @h2 %></h2>
    <div class="cardsCollection">
      <% @cla.all.sample(4).each do |el| %>
      <% @mod = el %>
      <%= render @cardType %>
      <% end %>
    </div>
    <%= render "but" %>
  </div>
</div>

app/views/application/_articleCard.html.erb
<div class="acticleCard">
  <%= link_to (article_path(@mod)) do %>
    <div class="info">
      <p>Статья</p>
      <h3><%= @mod.header %></h3>
      <p>Читать статью</p>
    </div>
    <div class="image">
      <div class="shadow">

      </div>
      <% if @mod.cover.url %>
        <%= image_tag @mod.cover.url%>
      <% else %>
        <%= image_tag asset_path("asep1.jpg")%>
      <% end %>
    </div>
  <% end %>
</div>

app/views/application/_but.html.erb
<div class="but">
  <% if method == :post %>
    <%= link_to rout, method: method do %>
    <span><%= mes %></span>
    <% end %>
  <% else %>
    <%= link_to rout do %>
    <span><%= mes %></span>
    <% end %>
  <% end %>
</div>

app/views/application/_footer.html.erb
<footer>
  <div class="body">
    <div class="info">
      <ul>
        <li>Пользоватлям</li>
        <li>О нас</li>
        <li>Бренды</li>
        <li>Каталог</li>
        <li>Статьи</li>
      </ul>
      <ul>
        <li>EP</li>
        <li>Профиль</li>
        <li>Избранное</li>
        <li>Тест на определение <br> типа кожи</li>
      </ul>
      <ul>
        <li>Компаниям</li>
        <li>Сотрудничество</li>
        <li>Эксперты</li>
      </ul>
    </div>
    <div class="conect">
      <div class="formArea">
        <span>Подпишитесь на рассылку</span>
        <div class="form">
          <span>Введите e-mail</span>
          <%= image_tag(asset_path("icons/arrows/next.png")) %>
        </div>
        <div class="check">
          <%= image_tag(asset_path("icons/checkBolls/white/active.png")) %>
          <span>Я согласен на обработку личных данных</span>
        </div>
      </div>
      <div class="soialNetworks">
        <%= image_tag(asset_path("icons/sosialNetworks/telegram.png")) %>
        <%= image_tag(asset_path("icons/sosialNetworks/fasebook.png")) %>
        <%= image_tag(asset_path("icons/sosialNetworks/instagram.png")) %>
        <%= image_tag(asset_path("icons/sosialNetworks/vkontakte.png")) %>
      </div>
    </div>
  </div>
  <div class="footer">
    <div class="line"></div>
    <div class="ps">
      <span>Россия, Москва</span>
      <span>Mirea 2020</span>
    </div>
  </div>
</footer>

app/views/application/_menubar.html.erb
<div class="menubar">
  <div class="up">
    <%= image_tag asset_path("icons/burger.png"), class: "burger" %>
    <div class="left">
      <div class="logo">
        <%= link_to image_tag(asset_path("logos/LogoFull.png")), detach_landing_path %>
      </div>
      <ul>
        <li>
          <% if controller.class == DetachController && controller.action_name == "index" %>
          <%= link_to "Главная", root_path, class: "active" %>
          <div></div>
          <% else %>
          <%= link_to "Главная", root_path %>
          <% end %>
          <div></div>
        </li>
        <li>
          <% if controller.class == ProductsController %>
          <%= link_to "Каталог", catalogs_path, class: "active" %>
          <div></div>
          <% else %>
          <%= link_to "Каталог", catalogs_path %>
          <% end %>
          <div></div>
        </li>
        <li>
          <% if controller.class == BrandsController %>
          <%= link_to "Бренды", brands_path, class: "active" %>
          <div></div>
          <% else %>
          <%= link_to "Бренды", brands_path %>
          <% end %>
          <div></div>
        </li>
        <li>
          <% if controller.class == ArticlesController %>
          <%= link_to "Статьи", articles_path, class: "active" %>
          <div></div>
          <% else %>
          <%= link_to "Статьи", articles_path %>
          <% end %>
          <div></div>
        </li>
      </ul>
    </div>
    <div class="rigth">
      <% if user_signed_in? %>
        <div class="cearth">
            <%= image_tag(asset_path("icons/loup/inactive.png")) %>
        </div>
        <div class="userInfo">
          <%= link_to (profile_favorites_path(current_user.profile.id)) do %>
          <div class="icon follow">
            <% if controller.class ==  FavoritesController%>
              <%= image_tag(asset_path("icons/follow/activeWhite.png")) %>
            <% else %>
              <%= image_tag(asset_path("icons/follow/staticWhite.png")) %>
            <% end %>
            </div>
          <% end %>
          <%= link_to(profile_path(current_user.id)) do %>
            <div class="icon profile">
              <% if controller.class == ProfilesController%>
                <%= image_tag(asset_path("icons/profile/active.png")) %>
              <% else %>
                <%= image_tag(asset_path("icons/profile/inactive.png")) %>
              <% end %>
            </div>
          <% end %>
      </div>
      <% else %>
        <div class="cearth">
          <%= image_tag(asset_path("icons/loup/inactive.png")) %>
        </div>
        <div class="userInfo">
          <%= link_to('Login', new_user_session_path) %>
          <%= link_to('Sign Up', new_user_registration_path) %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="forMobile">
    <ul>
      <li> <%= link_to "Главная", root_path %> </li>
      <li> <%= link_to "Каталог", catalogs_path %> </li>
      <li> <%= link_to "Бренды", brands_path %> </li>
      <li> <%= link_to "Статьи", articles_path %> </li>
      <% if user_signed_in? %>
        <li class="black"><%= link_to "Избранное", (profile_favorites_path(current_user.profile.id))%></li>
        <li class="black"><%= link_to "Профиль", (profile_path(current_user.id)) %></li>
        <li class="black"><%= link_to "Выход", (profile_path(current_user.id)) %></li>
      <% else %>
        <li class="black"><%= link_to('Регистрация', new_user_registration_path) %></li>
        <li class="black"><%= link_to('Вход', new_user_session_path) %></li>
      <% end %>
    </ul>
  </div>

  <% if controller.class == ProductsController && controller.action_name == "catalog" %>
    <div class="crumb_bar">
      <!--
      Начиная с первой группы
      на странице продуктов
      на странице бренда -->
      <p><%= link_to "Каталог", catalogs_path %></p>
      <div class="sir"></div>
      <p><%= link_to ProductGroup.find(params[:id]).name, catalog_path(params[:id]) %></p>
    </div>
  <% end %>
  <% if controller.class == ProductsController && controller.action_name == "show" %>
    <div class="crumb_bar">
      <!--
      Начиная с первой группы
      на странице продуктов
      на странице бренда -->
      <p><%= link_to "Каталог", catalogs_path, class: "active" %></p>
      <div class="sir"></div>
      <%= link_to ProductGroup.find(@product.product_types.first.product_group_id).name, catalog_path(ProductGroup.find(@product.product_types.first.product_group_id).id) %>
      <div class="sir"></div>
      <p><%= @product.product_types.first.name %></p>
    </div>
  <% end %>
</div>

app/views/application/_productBlock.html.erb
<div class="block products">
  <div class="pattern">
    <%#= image_tag(asset_path(@imagePath)) %>
  </div>
  <div class="content">
    <h2><%= @h2 %></h2>
    <div class="cardsCollection">
      <% @cla.all.sample(5).each do |el| %>
      <% @mod = el %>
      <%= render @cardType %>
      <% end %>
    </div>
    <%= render "but" %>
  </div>
</div>

app/views/application/_productCard.html.erb
<div class="productCard">
  <%= link_to (brand_product_path(@mod.brand_id, @mod.id)) do %>
    <div class="image">
      <% if @mod.image.url %>
        <%= image_tag @mod.image.url %>
      <% else %>
        <%= image_tag(asset_path("apsent.jpg")) %>
      <% end %>
      <div class="lables">
        <div class="spetial">
          <span>Новинка</span>
        </div>
        <%= image_tag(asset_path("icons/follow/staticWhite.png")) %>
      </div>

    </div>
    <div class="icons">
      <%= image_tag(asset_path("icons/evitattion/god.png")) %>
      <%= image_tag(asset_path("icons/effect/god.png")) %>
    </div>
    <div class="info">
      <h3><%= @mod.name %></h3>
      <p><%= @mod.view unless @mod.view == nil %></p>
    </div>
  <% end %>
</div>